### ISSUE TITLE
Unable to run command `exec`

### ISSUE THREAD

**Issue by alexbowers** [canton7/s3-tar-backup#5]
```
/var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/lib/s3_tar_backup.rb:349:in `exec': Unable to run command. See above output for clues. (RuntimeError)
	from /var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/lib/s3_tar_backup.rb:218:in `backup'
	from /var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/lib/s3_tar_backup.rb:212:in `backup_full'
	from /var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/lib/s3_tar_backup.rb:147:in `perform_backup'
	from /var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/lib/s3_tar_backup.rb:70:in `block in run'
	from /var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/lib/s3_tar_backup.rb:65:in `each'
	from /var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/lib/s3_tar_backup.rb:65:in `run'
	from /var/lib/gems/2.3.0/gems/s3-tar-backup-1.1.3/bin/s3-tar-backup:7:in `<top (required)>'
	from /usr/local/bin/s3-tar-backup:23:in `load'
	from /usr/local/bin/s3-tar-backup:23:in `<main>'
```

This is the result of us trying to backup a 160G directory.

The output above is the "tar" output from putting it in verbose mode.

Any ideas how we can debug this, or is large backup directories not supported?

**Comment by canton7** [comment]
That means that the `tar` command returned a non-zero status code. I'm afraid this is between you and `tar`.
